name: Test with pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dev package dependencies
      run: |
        sudo apt update && sudo apt install -y \
          xvfb \
          libxkbcommon-x11-0 \
          alsa-utils \
          pyqt5-dev-tools
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel flake8
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . \
          --count \
          --select=E9,F63,F7,F82 \
          --show-source \
          --statistics \
          --extend-exclude=venv

        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . \
          --count \
          --exit-zero \
          --max-complexity=10 \
          --max-line-length=127 \
          --statistics \
          --extend-exclude=venv

    - name: Run unit tests
      run: |
        pytest
